/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#444651",
        "on-primary-fixed": "#00164e",
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#a4acc5",
        "surface-container-low": "#eff4ff",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#25005a",
        "secondary-fixed": "#eaddff",
        "surface-variant": "#d3e4fe",
        "on-secondary-container": "#fffbff",
        "surface-container-high": "#dce9ff",
        "primary-fixed": "#dce1ff",
        "on-secondary": "#ffffff",
        "secondary-container": "#8a4cfc",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed": "#dae2fd",
        "tertiary": "#222a3e",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b6c4ff",
        "background": "#f8f9ff",
        "surface-tint": "#4059aa",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed-variant": "#264191",
        "primary": "#00236f",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3f465c",
        "inverse-primary": "#b6c4ff",
        "error-container": "#ffdad6",
        "on-background": "#0b1c30",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-tertiary-fixed": "#131b2e",
        "tertiary-container": "#384055",
        "tertiary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "surface": "#f8f9ff",
        "secondary": "#712ae2",
        "outline": "#757682",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#d2bbff",
        "on-surface": "#0b1c30",
        "outline-variant": "#c5c5d3",
        "on-primary-container": "#90a8ff",
        "primary-container": "#1e3a8a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "margin-sm": "1rem",
        "gutter": "1rem",
        "gutter-sm": "0.75rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "space-lg": "1.25rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "margin": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-mono-lg": ["JetBrains Mono", "monospace"],
        "data-mono-md": ["JetBrains Mono", "monospace"],
        "data-mono-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-mono-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "data-mono-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "500" }],
        "data-mono-lg": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
